kits:
  default:
    delay: 60
    items:
      - IRON_SWORD, 1
      - DIAMOND, 10
  example:
    delay: 60
    items:
      - GOLD_INGOT, 5
      - IRON_INGOT, 5
      - DIAMOND, 5
      - EMERALD, 5

messages:
  usage: "Command usage: /kit [kit name] or /kit list"
  permission: "You do not have permission to use this kit."
  no_kits: "There are no kits setup in the 'config.yml'."
  does_not_exist: "The specified kit does not exists, use /kit list to see available kits."
  invalid_item: "{kit}: {material} does not exist. Please make sure it is spelled and formatted correctly."