name: SimpleKits
version: @version@
main: me.amazonpriime.simplekits.SimpleKits
authors: [AmazonPriime]
description: Very simple kits plugin.
commands:
  kit:
    description: Gives a player items depending on what kit they use.
  kits:
    description: Gives a player a list of the kits available to them.